### ISSUE TITLE
how to set the Log's min height and max height?

### ISSUE THREAD

**Issue by yiya1989** [louis-she/gradio-log#1]
Like the screenshot, I want to set the `height: 336px` to `height: 800px` or the xterm auto fix the height, how can I do? Thanks!
![image](https://github.com/louis-she/gradio-log/assets/3204394/19cdfde5-06ce-4cea-ae88-15f3f9fba9a9)

**Comment by yiya1989** [comment]
哈哈。发现老哥是中国人啊，就是想请教下，我再Log 里面可以设置固定高度或者自适应高度吗。。默认的有点太矮了

**Comment by SebastianKohler** [comment]
You can set an id-attribute on the component HTML using the `elem_id` property on the `Log` class:

```Python
Log("log_file.log", elem_id="gradio-log-comp-id")
```

And then add the CSS styling to the Gradio `Blocks` class using the `css` property:

```Python
import gradio as gr

with gr.Blocks(css="#gradio-log-comp-id {min-height: 200px; max-height: 800px}") as demo:
   # your Gradio components
```

I think the `Interface` class also has the `css` property.

**Comment by louis-she** [comment]
@yiya1989 这个不是代码写死的，前端直接用了 Gradio 的 Block，应该是撑满 gr.Row 的高度才对。你可以试试通过 gr.Row 的参数来调整高度：

https://www.gradio.app/docs/gradio/row

**Comment by louis-she** [comment]
added a height props of `Log`
