### ISSUE TITLE
多人使用情况下，读磁盘日志内容不同步

### ISSUE THREAD

**Issue by boin** [louis-she/gradio-log#2]
**使用场景**：多用户同时在服务器上使用某个python服务，需要把控制台所有日志dump到页面上。

**日志采集**：把python标准输入重定向到 tee 写入文件。
``` python3 -u webui.py 2>&1 | stdbuf -oL -eL tee -i logs/ui.log ```

**页面呈现**：导入并使用本组件
```from gradio_log import Log
def get_docker_logs():
    base_path = "./logs/ui.log"
    log_path = base_path
    return log_path

    Log(
        get_docker_logs(),
        dark=True,
        xterm_font_size=12,
        render=bool(get_docker_logs()),
     )
```

**期待效果**：类似在控制台上 tail -f logs/ui.log 一样，实时滚动显示日志内容，无论开几个tty / tail 命令都有效

**目前问题**：在单人/多人同时打开并使用同一个界面的情况下，log 界面会随机的停止日志更新，刷新后也不生效。需要重启整个webui才正常

不是很熟悉python和gradio，猜测多前端请求导致了 io 输出被随机分配到不同页面了 ？ 我有什么办法可以粗暴解决此问题？谢谢！

**Comment by louis-she** [comment]
是个已知问题，等我有空了来修复吧，现在似乎 Gradio 5 中也不 work 了。

**Comment by louis-she** [comment]
Gradio 5 适配了，剩下这个同步问题 ...

**Comment by louis-she** [comment]
已支持多个 tab 同时查看
