### ISSUE TITLE
Set max log length gradio user sees?

### ISSUE THREAD

**Issue by DrewThomasson** [louis-she/gradio-log#3]
Is there a way to make it less resource intensive so that the gradio user has a max log size?

Prioritizing the latest logs of course that is

**Comment by louis-she** [comment]
do you mean the `scrollback` option of xterm.js ?

**Comment by DrewThomasson** [comment]
lol thx didn't know it was already an option

Byeah so then it doesn't have to reload the full log file everytime  it updates for the user
